let content = document.querySelector('.js-generated.content')
let header = document.createElement('h1')
header.setAttribute('class', 'dog-name')
header.append('Rizzo')
content.append(header)
let dogBio = document.createElement('div')
dogBio.setAttribute('class', 'dog-content')
let dogPic = document.createElement('img')
dogPic.setAttribute('class', 'dog-image')
dogPic.setAttribute('src', './assets/rizzo.jpg')
dogBio.append(dogPic)
let dogDet = document.createElement('div')
dogDet.setAttribute('class', 'dog-details')
let desc = document.createElement('h3')
desc.append('Description:')
dogDet.append(desc)
let dogP = document.createElement('p')
dogP.append("This gentle dog is aloof toward her owner, and never comes when called. She always acts as though any stranger she meets will harm her, and dislikes other animals.")
dogDet.append(dogP)
let feed = document.createElement('h3')
feed.append('Feeding Times:')
dogDet.append(feed)
let times = document.createElement('ul')
let firstFeed = document.createElement('li')
firstFeed.append('9:00 am')
times.append(firstFeed)
let secondFeed = document.createElement('li')
secondFeed.append('12:00 pm')
times.append(secondFeed)
let thirdFeed = document.createElement('li')
thirdFeed.append('5:00 pm')
times.append(thirdFeed)
dogDet.append(times)
dogBio.append(dogDet)
content.append(dogBio)